config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :regisrations => "my_registrations" , omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :show, :new, :edit, :destroy]
  resources :friend_requests, only: [:create, :destroy, :show, :index]
  resources :friendships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments

  post 'posts/:id/edit', to: 'posts#update'
  post 'posts/new', to: 'posts#create'

  get 'likes', to: 'posts#index'
  post 'comments/new', to: 'comments#create'

  post 'users/:id', to: 'posts#create'





end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :post

    validates :user, :post, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        post = Post.find(params[:comment][:post_id])
        comment = post.comments.build(user: current_user, body: params[:comment][:body])
        if comment.save
            redirect_to request.referrer
        else
            flash[:notice] = 'We could not save your comment.  Please try again.'
            redirect_to request.referrer
        end
    end

    def destroy
        comment = Comment.find(params[:id])
        comment.destroy
        redirect_to request.referrer
    end
end

app/helpers/comments_helper.rb
module CommentsHelper

    def find_comments(post)
        comments = Comment.includes(:user).where(post_id: post.id)
        comments
    end
end

app/views/comments/_comments.html.erb
<% comments.each do |c| %>
<i> <strong> Comment by: 
     <%= link_to c.user.first_name, user_path(c.user.id) %></i> </strong>
    <div><%= c.body %></div>
    <% if c.user == current_user %>
        <%= link_to 'Delete comment', c, :method => :delete, :confirm => "Are you sure?" %>
    <% end %>
<% end %>

app/views/comments/_new_comment.html.erb
<div>
<%= form_for :comment, url: new_comment_path(post.id) do |f| %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.text_area :body, placeholder: "What would you like to comment?" %> <br>
    <%= f.submit "Submit comment" %>
<% end %>
</div>