config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :regisrations => "my_registrations" , omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :show, :new, :edit, :destroy]
  resources :friend_requests, only: [:create, :destroy, :show, :index]
  resources :friendships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments

  post 'posts/:id/edit', to: 'posts#update'
  post 'posts/new', to: 'posts#create'

  get 'likes', to: 'posts#index'
  post 'comments/new', to: 'comments#create'

  post 'users/:id', to: 'posts#create'





end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  validates :email, :encrypted_password, presence: true

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships 

  has_many :posts, dependent: :destroy

  has_many :received_friend_requests, class_name: "FriendRequest", foreign_key: :requestee_id, dependent: :destroy
  
  has_many :sent_friend_requests, class_name:  'FriendRequest', foreign_key: :requester_id, dependent: :destroy

  has_many :likes, dependent: :destroy


  has_many :comments, dependent: :destroy
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name   # assuming the user model has a name
      user.last_name = auth.info.last_name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
  end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
    skip_before_action :verify_authenticity_token, only: :facebook
  
    def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @posts = Post.includes(:user).where(user_id: @user.id).order(created_at: :desc )
    end

end

app/helpers/users_helper.rb
module UsersHelper
    #function to shrink all friends query into single object
    def friends
        current_user.friends.all
    end
    

    def find_request(user)
        FriendRequest.where('requester_id = ? AND requestee_id = ?', user.id, current_user.id)[0]
    end

    def sent_requests
        requests = FriendRequest.includes(:requestee).where('requester_id = ?', current_user.id)
        return [-1] if requests.nil?
        requests = requests.map { |r| r.requestee }
        requests
    end

    def received_requests
        requests = FriendRequest.includes(:requester).where('requestee_id = ?', current_user.id)
        return [-1] if requests.nil?
        requests = requests.map { |r| r.requester }
        requests
    end

    def friend_request_list
        requests = FriendRequest.includes(:requester).where(requestee_id: current_user.id).limit(10)
        requests
    end


end

app/views/users/index.html.erb
<h2> <%= @user.first_name %> <%= @user.last_name %> </h2>

app/views/users/show.html.erb
Welcome to the profile of: <br>

<h1> <%= @user.first_name %> <%= @user.last_name %> </h1> 
<div>
    <%= gravatar_image_tag(@user.email, :gravatar => { :size => 100 })%>
</div> 
<br> <br> 

<%= @user.first_name %>'s friends:
<% @user.friends.each do |friend| %>

    <div> 
        <strong> <i> 
        <%= link_to friend.first_name, user_path(friend) %></i> </h2>
    </div>

    
<% end %>


<% if friends.include?(@user) %>
    You and <%= @user.first_name %> are friends.
<br> <br>
<% elsif sent_requests.include?(@user)%>
    Friend Request Sent
<br> <br>
<% elsif received_requests.include?(@user) %>
    <%= button_to 'Accept Friend Request', friendships_path(friend_request: find_request(@user)) %>
    <%= button_to 'Reject Friend Request', friend_request_path(find_request(@user).id), method: 'delete' %>
<br> <br>
<% elsif @user != current_user %>
    Would you like to request <%= @user.first_name %> to be your friend?
    <%= button_to 'Request to be Friends', friend_requests_path(user_id: @user.id) %>
<br> <br>
<% end %>

<%= @user.first_name%>'s Posts:
<% if (current_user == @user) or (friends.include? @user) %>
    <% if @posts.any? %>
        <%= render 'posts/post', { posts: @posts, friends: @friends} %>
    <% end %>
<% end %>